### ISSUE TITLE
Lua Error once added to server.

### ISSUE THREAD

**Issue by Jackralph96** [Leeous/medic-kiosk#7]
Addon is set up using a custom job works perfectly with no issues but the auto add lua seems to kick out an error along the lines of 

```Lua
[ERROR] A runtime error has occurred in "lua/autorun/autoadd.lua" on line 11.
The best help I can give you is this:

Corrupt entity: Medic Kiosk!
This entity does not have a unique command.

Hints:
	- There must be some other entity that has the same thing for 'cmd'.
	- Fix this by changing the 'cmd' field of your entity to something else.

The responsibility for the error above lies with (the authors of) one (or more) of these files:
	1. lua/autorun/autoadd.lua on line 11
------- End of Simplerr error -------
```
addon works fine though.
This is when  medickiosk_disableautoadd is set to 1 or true seems to make no differance.

**Comment by Leeous** [comment]
This issue should be resolved. It was my fault. ᵈᵃᵐᵐᶦᵗ

_Sent from my Huawei Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Jackralph96** [comment]
No problem i'll update it later today and see if it's fixed for you.

Best Regards
Jack Ralph
